name: portfolio
description: Kristhyan de Matos Maia

version: 1.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/noise.png
    - assets/unifesspa.svg
    - assets/experiences/
    - assets/icons/
    - assets/projects/
